goto ResetInputGui

;Map Buttons to new actions


1joy1::
buttonMatrix["1joy1"].ButtonDown()
Return
1joy2::
buttonMatrix["1joy2"].ButtonDown()
Return
1joy3::
buttonMatrix["1joy3"].ButtonDown()
Return
1joy4::
buttonMatrix["1joy4"].ButtonDown()
Return
1joy5::
buttonMatrix["1joy5"].ButtonDown()
Return
1joy6::
buttonMatrix["1joy6"].ButtonDown()
Return
1joy7::
buttonMatrix["1joy7"].ButtonDown()
Return
1joy8::
buttonMatrix["1joy8"].ButtonDown()
Return
1joy9::
buttonMatrix["1joy9"].ButtonDown()
Return
1joy10::
buttonMatrix["1joy10"].ButtonDown()
Return
1joy11::
buttonMatrix["1joy11"].ButtonDown()
Return
1joy12::
buttonMatrix["1joy12"].ButtonDown()
Return
1joy13::
buttonMatrix["1joy13"].ButtonDown()
Return
1joy14::
buttonMatrix["1joy14"].ButtonDown()
Return
1joy15::
buttonMatrix["1joy15"].ButtonDown()
Return
1joy16::
buttonMatrix["1joy16"].ButtonDown()
Return
1joy17::
buttonMatrix["1joy17"].ButtonDown()
Return
1joy18::
buttonMatrix["1joy18"].ButtonDown()
Return
1joy19::
buttonMatrix["1joy19"].ButtonDown()
Return
1joy20::
buttonMatrix["1joy20"].ButtonDown()
Return
1joy21::
buttonMatrix["1joy21"].ButtonDown()
Return
1joy22::
buttonMatrix["1joy22"].ButtonDown()
Return
1joy23::
buttonMatrix["1joy23"].ButtonDown()
Return
1joy24::
buttonMatrix["1joy24"].ButtonDown()
Return
1joy25::
buttonMatrix["1joy25"].ButtonDown()
Return
1joy26::
buttonMatrix["1joy26"].ButtonDown()
Return
1joy27::
buttonMatrix["1joy27"].ButtonDown()
Return
1joy28::
buttonMatrix["1joy28"].ButtonDown()
Return
1joy29::
buttonMatrix["1joy29"].ButtonDown()
Return
1joy30::
buttonMatrix["1joy30"].ButtonDown()
Return
1joy31::
buttonMatrix["1joy31"].ButtonDown()
Return
1joy32::
buttonMatrix["1joy32"].ButtonDown()
Return
2joy1::
buttonMatrix["2joy1"].ButtonDown()
Return
2joy2::
buttonMatrix["2joy2"].ButtonDown()
Return
2joy3::
buttonMatrix["2joy3"].ButtonDown()
Return
2joy4::
buttonMatrix["2joy4"].ButtonDown()
Return
2joy5::
buttonMatrix["2joy5"].ButtonDown()
Return
2joy6::
buttonMatrix["2joy6"].ButtonDown()
Return
2joy7::
buttonMatrix["2joy7"].ButtonDown()
Return
2joy8::
buttonMatrix["2joy8"].ButtonDown()
Return
2joy9::
buttonMatrix["2joy9"].ButtonDown()
Return
2joy10::
buttonMatrix["2joy10"].ButtonDown()
Return
2joy11::
buttonMatrix["2joy11"].ButtonDown()
Return
2joy12::
buttonMatrix["2joy12"].ButtonDown()
Return
2joy13::
buttonMatrix["2joy13"].ButtonDown()
Return
2joy14::
buttonMatrix["2joy14"].ButtonDown()
Return
2joy15::
buttonMatrix["2joy15"].ButtonDown()
Return
2joy16::
buttonMatrix["2joy16"].ButtonDown()
Return
2joy17::
buttonMatrix["2joy17"].ButtonDown()
Return
2joy18::
buttonMatrix["2joy18"].ButtonDown()
Return
2joy19::
buttonMatrix["2joy19"].ButtonDown()
Return
2joy20::
buttonMatrix["2joy20"].ButtonDown()
Return
2joy21::
buttonMatrix["2joy21"].ButtonDown()
Return
2joy22::
buttonMatrix["2joy22"].ButtonDown()
Return
2joy23::
buttonMatrix["2joy23"].ButtonDown()
Return
2joy24::
buttonMatrix["2joy24"].ButtonDown()
Return
2joy25::
buttonMatrix["2joy25"].ButtonDown()
Return
2joy26::
buttonMatrix["2joy26"].ButtonDown()
Return
2joy27::
buttonMatrix["2joy27"].ButtonDown()
Return
2joy28::
buttonMatrix["2joy28"].ButtonDown()
Return
2joy29::
buttonMatrix["2joy29"].ButtonDown()
Return
2joy30::
buttonMatrix["2joy30"].ButtonDown()
Return
2joy31::
buttonMatrix["2joy31"].ButtonDown()
Return
2joy32::
buttonMatrix["2joy32"].ButtonDown()
Return
3joy1::
buttonMatrix["3joy1"].ButtonDown()
Return
3joy2::
buttonMatrix["3joy2"].ButtonDown()
Return
3joy3::
buttonMatrix["3joy3"].ButtonDown()
Return
3joy4::
buttonMatrix["3joy4"].ButtonDown()
Return
3joy5::
buttonMatrix["3joy5"].ButtonDown()
Return
3joy6::
buttonMatrix["3joy6"].ButtonDown()
Return
3joy7::
buttonMatrix["3joy7"].ButtonDown()
Return
3joy8::
buttonMatrix["3joy8"].ButtonDown()
Return
3joy9::
buttonMatrix["3joy9"].ButtonDown()
Return
3joy10::
buttonMatrix["3joy10"].ButtonDown()
Return
3joy11::
buttonMatrix["3joy11"].ButtonDown()
Return
3joy12::
buttonMatrix["3joy12"].ButtonDown()
Return
3joy13::
buttonMatrix["3joy13"].ButtonDown()
Return
3joy14::
buttonMatrix["3joy14"].ButtonDown()
Return
3joy15::
buttonMatrix["3joy15"].ButtonDown()
Return
3joy16::
buttonMatrix["3joy16"].ButtonDown()
Return
3joy17::
buttonMatrix["3joy17"].ButtonDown()
Return
3joy18::
buttonMatrix["3joy18"].ButtonDown()
Return
3joy19::
buttonMatrix["3joy19"].ButtonDown()
Return
3joy20::
buttonMatrix["3joy20"].ButtonDown()
Return
3joy21::
buttonMatrix["3joy21"].ButtonDown()
Return
3joy22::
buttonMatrix["3joy22"].ButtonDown()
Return
3joy23::
buttonMatrix["3joy23"].ButtonDown()
Return
3joy24::
buttonMatrix["3joy24"].ButtonDown()
Return
3joy25::
buttonMatrix["3joy25"].ButtonDown()
Return
3joy26::
buttonMatrix["3joy26"].ButtonDown()
Return
3joy27::
buttonMatrix["3joy27"].ButtonDown()
Return
3joy28::
buttonMatrix["3joy28"].ButtonDown()
Return
3joy29::
buttonMatrix["3joy29"].ButtonDown()
Return
3joy30::
buttonMatrix["3joy30"].ButtonDown()
Return
3joy31::
buttonMatrix["3joy31"].ButtonDown()
Return
3joy32::
buttonMatrix["3joy32"].ButtonDown()
Return
4joy1::
buttonMatrix["4joy1"].ButtonDown()
Return
4joy2::
buttonMatrix["4joy2"].ButtonDown()
Return
4joy3::
buttonMatrix["4joy3"].ButtonDown()
Return
4joy4::
buttonMatrix["4joy4"].ButtonDown()
Return
4joy5::
buttonMatrix["4joy5"].ButtonDown()
Return
4joy6::
buttonMatrix["4joy6"].ButtonDown()
Return
4joy7::
buttonMatrix["4joy7"].ButtonDown()
Return
4joy8::
buttonMatrix["4joy8"].ButtonDown()
Return
4joy9::
buttonMatrix["4joy9"].ButtonDown()
Return
4joy10::
buttonMatrix["4joy10"].ButtonDown()
Return
4joy11::
buttonMatrix["4joy11"].ButtonDown()
Return
4joy12::
buttonMatrix["4joy12"].ButtonDown()
Return
4joy13::
buttonMatrix["4joy13"].ButtonDown()
Return
4joy14::
buttonMatrix["4joy14"].ButtonDown()
Return
4joy15::
buttonMatrix["4joy15"].ButtonDown()
Return
4joy16::
buttonMatrix["4joy16"].ButtonDown()
Return
4joy17::
buttonMatrix["4joy17"].ButtonDown()
Return
4joy18::
buttonMatrix["4joy18"].ButtonDown()
Return
4joy19::
buttonMatrix["4joy19"].ButtonDown()
Return
4joy20::
buttonMatrix["4joy20"].ButtonDown()
Return
4joy21::
buttonMatrix["4joy21"].ButtonDown()
Return
4joy22::
buttonMatrix["4joy22"].ButtonDown()
Return
4joy23::
buttonMatrix["4joy23"].ButtonDown()
Return
4joy24::
buttonMatrix["4joy24"].ButtonDown()
Return
4joy25::
buttonMatrix["4joy25"].ButtonDown()
Return
4joy26::
buttonMatrix["4joy26"].ButtonDown()
Return
4joy27::
buttonMatrix["4joy27"].ButtonDown()
Return
4joy28::
buttonMatrix["4joy28"].ButtonDown()
Return
4joy29::
buttonMatrix["4joy29"].ButtonDown()
Return
4joy30::
buttonMatrix["4joy30"].ButtonDown()
Return
4joy31::
buttonMatrix["4joy31"].ButtonDown()
Return
4joy32::
buttonMatrix["4joy32"].ButtonDown()
Return
5joy1::
buttonMatrix["5joy1"].ButtonDown()
Return
5joy2::
buttonMatrix["5joy2"].ButtonDown()
Return
5joy3::
buttonMatrix["5joy3"].ButtonDown()
Return
5joy4::
buttonMatrix["5joy4"].ButtonDown()
Return
5joy5::
buttonMatrix["5joy5"].ButtonDown()
Return
5joy6::
buttonMatrix["5joy6"].ButtonDown()
Return
5joy7::
buttonMatrix["5joy7"].ButtonDown()
Return
5joy8::
buttonMatrix["5joy8"].ButtonDown()
Return
5joy9::
buttonMatrix["5joy9"].ButtonDown()
Return
5joy10::
buttonMatrix["5joy10"].ButtonDown()
Return
5joy11::
buttonMatrix["5joy11"].ButtonDown()
Return
5joy12::
buttonMatrix["5joy12"].ButtonDown()
Return
5joy13::
buttonMatrix["5joy13"].ButtonDown()
Return
5joy14::
buttonMatrix["5joy14"].ButtonDown()
Return
5joy15::
buttonMatrix["5joy15"].ButtonDown()
Return
5joy16::
buttonMatrix["5joy16"].ButtonDown()
Return
5joy17::
buttonMatrix["5joy17"].ButtonDown()
Return
5joy18::
buttonMatrix["5joy18"].ButtonDown()
Return
5joy19::
buttonMatrix["5joy19"].ButtonDown()
Return
5joy20::
buttonMatrix["5joy20"].ButtonDown()
Return
5joy21::
buttonMatrix["5joy21"].ButtonDown()
Return
5joy22::
buttonMatrix["5joy22"].ButtonDown()
Return
5joy23::
buttonMatrix["5joy23"].ButtonDown()
Return
5joy24::
buttonMatrix["5joy24"].ButtonDown()
Return
5joy25::
buttonMatrix["5joy25"].ButtonDown()
Return
5joy26::
buttonMatrix["5joy26"].ButtonDown()
Return
5joy27::
buttonMatrix["5joy27"].ButtonDown()
Return
5joy28::
buttonMatrix["5joy28"].ButtonDown()
Return
5joy29::
buttonMatrix["5joy29"].ButtonDown()
Return
5joy30::
buttonMatrix["5joy30"].ButtonDown()
Return
5joy31::
buttonMatrix["5joy31"].ButtonDown()
Return
5joy32::
buttonMatrix["5joy32"].ButtonDown()
Return